# Generated by Django 6.1.1 on 2026-09-28 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('opis_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('coordinate_source', models.TextField(blank=True)),
                ('source_rows', models.PositiveIntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='planner_sta_latitud_cbe592_idx')],
            },
        ),
    ]
